# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-cm
data:
  index.html: |
    <h1>Hello from ConfigMap</h1>
  default.conf: |
    server { listen 80; root /usr/share/nginx/html; index index.html; }
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-pod
  labels:
    app: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx:stable
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: conf  
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf  # use "conf" volume but select only one file (default.conf)
  volumes:
    - name: html  # mount only index.html file (key) from ConfigMap under the name "html"
      configMap:
        name: web-cm
        items:
          - key: index.html
            path: index.html
    - name: conf  # mount all files (keys) from ConfigMap under the name "conf"
      configMap:
        name: web-cm
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-cm-svc
spec:
  type: NodePort
  selector:
    app: nginx-cm
  ports:
    - port: 80
      targetPort: 80

# kubectl apply -f volumes/configmap-as-volume.yaml
# minikube service nginx-cm-svc -n vol-lab
