apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api-pods
  template:
    metadata:
      labels:
        app: api-pods
    spec:
      containers:
      - name: app-api
        image: api:0.5.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: dev-config
