apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: calculator-api-pods
  template:
    metadata:
      labels:
        app: calculator-api-pods
    spec:
      containers:
      - name: calculator-api
        image: calculator-api:0.1.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom: []
