apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-backend-pods
  template:
    metadata:
      labels:
        app: calculator-backend-pods
    spec:
      containers:
      - name: calculator-backend
        image: calculator-backend:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom: []
