apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  type: ClusterIP
  selector:
    app: engine-pods
  ports:
  - port: 50009       # http://my-service:50009
    targetPort: 8080  # ENGINE_PORT
